#pragma once
/**
 * config.h (Android SDL layer)
 *
 * On desktop, this file defines compile-time filesystem paths (PREFS_PATH,
 * RESOURCE_PATH, INI_PATH etc.) generated by CMake.
 *
 * On Android, all paths are runtime values from internal storage, set via
 * EmulatorActivity.getArguments() and android_bridge.cpp.
 * We keep this header for compilation compatibility but leave the path
 * constants empty — they are never used in the Android code paths.
 */

#ifndef PROJECT_VERSION
#define PROJECT_VERSION "1.0.0"
#endif

#ifndef PROJECT_DESCRIPTION
#define PROJECT_DESCRIPTION "Loopy-MseDroid"
#endif

// These are unused on Android (paths come from JNI args) but must compile.
#include <filesystem>
namespace fs = std::filesystem;

static const fs::path PREFS_PATH    = "";
static const fs::path RESOURCE_PATH = "";
static const fs::path INI_PATH      = "loopymse.ini";

static const fs::path DEFAULT_BIOS_PATH       = "bios.bin";
static const fs::path DEFAULT_SOUND_BIOS_PATH = "soundbios.bin";
static const fs::path CONTROLLER_DB_PATH      = "gamecontrollerdb.txt";
